---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      publish_all: true
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

provisioner:
  name: chef_solo
  require_chef_omnibus: "13.1.31"

verifier:
  name: inspec

suites:
  - name: prod
    run_list:
      - role[phabricator]
      - recipe[chef_nginx]
      - role[phabricator-database]
      - recipe[phabricator]
    attributes:
      php-fpm:
        user: nobody
        group: nobody
        package_name: php71u-fpm
        service_name: php-fpm
    verifier:
      inspec_tests:
        - tests/packages.rb
        - tests/yum.rb
        - tests/nginx.rb
        - tests/mysql.rb
