---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

provisioner:
  name: chef_solo
  require_chef_omnibus: "13.1.31"
  client_rb:
    add_formatter: min
  solo_rb:
    file_atomic_update: false

suites:
  - name: prod
    run_list:
      - recipe[yum-epel]
      - recipe[yum-ius]
      - recipe[packages]
      - recipe[php]
      - recipe[php-fpm]
      - recipe[chef_nginx]
    attributes:
        packages-cookbook:
          git: install
          ntp: install
          yum-cron: install
          openssl: upgrade
        php:
          packages:
            - php71u-cli
            - php71u-fpm
            - pear1u
        php-fpm:
          user: nobody
          group: nobody
          package_name: php71u-fpm
          service_name: php-fpm
