name             'phabricator-omnibus'
license          'MIT Licence'
description      'phabricator project'
version          '0.0.1'

depends 'packages', '~> 1'
depends 'yum-epel', '~> 2.1'
depends 'yum-ius', '~> 2.2'
depends 'chef_nginx', '~> 6.1'
depends 'php-omnibus', '~> 0.1'
depends 'mariadb', '~> 1'
